[package]
name = "oc-sort"
version = "0.1.0"
edition = "2024"

[lib]
name = "oc_sort"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.14.0"
kfilter = "0.4.0"
nalgebra = "0.33.2"
pathfinding = "4.14.0"
pyo3 = { version="0.25.1", features=["extension-module"] }
